extends: substitution
message: To be consistent with the rest of the documentation, consider using '%s' instead of '%s'.
level: warning
ignorecase: true
# swap maps tokens in form of bad: good
swap:
  'sub-component': subcomponent
  'sub-components': subcomponents
  'sub component': subcomponent
  'sub components': subcomponents
  'use-case': 'use case'
  'usecase': 'use case'
